--- #YAML:1.0
name:                Tk-Month
version:             1.6
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Text::Abbrev:                  1
    Time::Local:                   1
    Tk:                            800
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
